export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const RESET_OFFSET = "RESET_OFFSET";
export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const LOAD_MORE_SEARCH_REQUEST = "LOAD_MORE_SEARCH_REQUEST";
export const LOAD_MORE_SEARCH = "LOAD_MORE_SEARCH";
export const STOP_FETCH_SEARCH = "STOP_FETCH_SEARCH";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";
export const MAKE_A_NEW_DATA_SEARCH = "MAKE_A_NEW_DATA_SEARCH";

export const ADD_ITEM_LIST = "ADD_ITEM_LIST";
export const HAS_ITEM = "HAS_ITEM";
export const MAKE_A_NEW_DATA = "MAKE_A_NEW_DATA";
export const REMOVE_ITEM_LIST = "REMOVE_ITEM_LIST";

export const PLAY_MUSIC = "PLAY_MUSIC";
export const PLAYLIST_MUSIC = "PLAYLIST_MUSIC";
export const PLAY_NEXT = "PLAY_NEXT";
export const PLAY_PREVIOUS = "PLAY_PREVIOUS";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const TOGGLE_LOOP = "TOGGLE_LOOP";
export const TOGGLE_SHUFFLE = "TOGGLE_SHUFFLE";
export const SET_PLAYING_STATE = "SET_PLAYING_STATE";
export const CLEAR_PLAYER_STATE = "CLEAR_PLAYER_STATE";
